AllCops:
  EnabledByDefault: true
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'app/views/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'test/**/*'
Bundler/GemComment:
  Enabled: false
Layout/LineLength:
  Max: 120
Lint/NumberConversion:
  Enabled: false
Lint/ConstantResolution:
  Enabled: false
Metrics/BlockLength:
  Max: 40
Metrics/MethodLength:
  Max: 40
Style/Copyright:
  Enabled: false
Style/MissingElse:
  Enabled: false
