language: ruby

services:
  - docker

branches:
  only:
    - develop
    - master

git:
  quiet: true
  submodules: false

before_script:
  - docker-compose build
  - docker-compose run notes bundle exec rails db:test:prepare
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - docker-compose run app bundle exec rails test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT