version: '3.5'
services:
  api:
    image: hugogilmar/squeeze-api
    build:
      context: .
    env_file: .env
    volumes:
      - ./:/opt/project/app:delegated
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache
      - web
    entrypoint: /opt/project/docker/entrypoint.sh
    command: /opt/project/docker/command.sh
    networks:
      squeeze-dev:
        aliases:
          - api.dev
    deploy:
      replicas: 1
  db:
    image: postgres:11.5-alpine
    env_file: .env
    volumes:
     - ./docker/db:/docker-entrypoint-initdb.d:delegated
    ports:
      - 5432:5432
    networks:
      squeeze-dev:
        aliases:
          - db.dev
    deploy:
      replicas: 1
  cache:
    image: redis:5.0-alpine
    env_file: .env
    ports:
      - 6379:6379
    networks:
      squeeze-dev:
        aliases:
          - cache.dev
    deploy:
      replicas: 1
  web:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      squeeze-dev:
        aliases:
          - web.dev
    deploy:
      replicas: 1
volumes:
  bundle:
    driver: local
networks:
  squeeze-dev:
    name: squeeze-dev
