default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'squeeze' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'db.dev' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { 'squeeze_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DATABASE_NAME") { 'squeeze_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { 'squeeze_production' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>
